In [1]:
%pip install flask scikit-learn pandas numpy joblib pickle

Requirement already satisfied: flask in c:\Users\Manaswin\AppData\Local\Programs\Python\Python311\Lib\site-packages (3.0.1)
Requirement already satisfied: scikit-learn in c:\Users\Manaswin\AppData\Local\Programs\Python\Python311\Lib\site-packages (1.3.2)
Requirement already satisfied: pandas in c:\Users\Manaswin\AppData\Local\Programs\Python\Python311\Lib\site-packages (2.1.4)
Requirement already satisfied: numpy in c:\Users\Manaswin\AppData\Local\Programs\Python\Python311\Lib\site-packages (1.26.4)
Requirement already satisfied: joblib in c:\Users\Manaswin\AppData\Local\Programs\Python\Python311\Lib\site-packages (1.3.2)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~jango (c:\Users\Manaswin\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (c:\Users\Manaswin\AppData\Local\Programs\Python\Python311\Lib\site-packages)
ERROR: Could not find a version that satisfies the requirement pickle (from versions: none)

[notice] A new release of pip is available: 26.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for pickle

In [2]:
import pandas as pd
import pickle

In [3]:
df = pd.read_csv('.\\dataset\\DEXINUS.csv')
print(df.shape)
df.head()

(1305, 2)

  observation_date  DEXINUS
0       26-04-2021    74.75
1       27-04-2021    74.58
2       28-04-2021    74.49
3       29-04-2021    74.07
4       30-04-2021    74.00

In [4]:
df = df.dropna()
print(df.shape)
df.head()

(1251, 2)

  observation_date  DEXINUS
0       26-04-2021    74.75
1       27-04-2021    74.58
2       28-04-2021    74.49
3       29-04-2021    74.07
4       30-04-2021    74.00

In [5]:
df['date'] = pd.to_datetime(df['observation_date'])
df['Day'] = df['date'].dt.day
df['Month'] = df['date'].dt.month
df['Year'] = df['date'].dt.year
df.head()

C:\Users\Manaswin\AppData\Local\Temp\ipykernel_24928\153324111.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['date'] = pd.to_datetime(df['observation_date'])

  observation_date  DEXINUS       date  Day  Month  Year
0       26-04-2021    74.75 2021-04-26   26      4  2021
1       27-04-2021    74.58 2021-04-27   27      4  2021
2       28-04-2021    74.49 2021-04-28   28      4  2021
3       29-04-2021    74.07 2021-04-29   29      4  2021
4       30-04-2021    74.00 2021-04-30   30      4  2021

In [6]:
X = df[['Day', 'Month', 'Year']]
y = df['DEXINUS']
df.head()

  observation_date  DEXINUS       date  Day  Month  Year
0       26-04-2021    74.75 2021-04-26   26      4  2021
1       27-04-2021    74.58 2021-04-27   27      4  2021
2       28-04-2021    74.49 2021-04-28   28      4  2021
3       29-04-2021    74.07 2021-04-29   29      4  2021
4       30-04-2021    74.00 2021-04-30   30      4  2021

In [7]:
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=False)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(1000, 3) (251, 3) (1000,) (251,)

In [8]:
model = SVR(kernel='rbf',C=1e3, gamma=0.1)
model = model.fit(X_train, y_train)

In [9]:
model_name = str(input('Enter the name to save the model (without extension): '))
with open(f"{model_name}.pkl", 'wb') as f:
    pickle.dump(model, f)

In [10]:
print(f'Model trained and saved as {model_name}.pkl')

Model trained and saved as nexus.pkl